### ISSUE TITLE
MSVC x64 does not support inline assembly

### ISSUE THREAD

**Issue by DrChat** [devernay/openfx-supportext#4]
Relevant to fast_mutex.h and tinythread.h - MSVC dropped support for __asm. 

EZ (compilation) fix is to remove _M_X64 check from
https://github.com/devernay/openfx-supportext/blob/5928879dc4d643aafb74260740259b4809f238b0/fast_mutex.h#L42

and

https://github.com/devernay/openfx-supportext/blob/5928879dc4d643aafb74260740259b4809f238b0/tinythread.h#L115

**Comment by devernay** [comment]
Hi,
I don't see a mention of it being dropped anywhere, can you point to a reference?
It seems to be still here:
https://docs.microsoft.com/en-us/cpp/assembler/inline/asm

Was it dropped from a specific _MSC_VER value?

**Comment by devernay** [comment]
OK, from https://docs.microsoft.com/en-us/cpp/assembler/inline/inline-assembler
"Inline assembly is not supported on the ARM and x64 processors."

**Comment by devernay** [comment]
Do you know if it was supported in previous versions?

**Comment by DrChat** [comment]
AFAIK they never supported it in 64-bit builds, only 32-bit.

Also, some more knowledge: As I'm aware, critical sections are implemented in usermode on Windows - AKA they're just as fast as the assembly solution you're using.

Of interest to you may be [InterlockedCompareExchange](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683560(v=vs.85).aspx) on Windows.

**Comment by devernay** [comment]
tinythread and fast_mutex both come from tinythread++.
I fixed a bug in fast_mutex.h, though, but I don't know if the MSVC version is also affected:
https://github.com/NatronGitHub/openfx-supportext/commit/126600ace503304373613f8a98a8166b3965196a
