### ISSUE TITLE
How to use ofxsFilter.h

### ISSUE THREAD

**Issue by alijaya** [devernay/openfx-supportext#7]
Hi, I want to ask how to use ofxsFilterInterpolate2D and ofxsFilterInterpolate2DSuper

For ofxsFilterInterpolate2D(fx, fy, *srcImg, blackOutside, *tmpPix) is kinda pretty clear to me.
fx and fy is the coordinate where we want to sample
*srcImg is the image data
blackOutside is whether we want to treat out of the bound of the pixel as 0 or nearest pixel
*tmpPix is for returning the value

But for ofxsFilterInterpolate2DSuper(fx, fy, Jxx, Jxy, Jyx, Jyy, *srcImg, blackOutside, *tmpPix) gets me confused
What is Jxx, Jxy, Jyx, Jyy?
In the documentation it says it's derivative, but I still don't get it.
Can you give me an example?

**Comment by devernay** [comment]
Jxx Jxy Jyx and Jyy are components of the Jacobian of the transform. This is used to supersample the image where it shrinks, and thus avoid aliasing artifacts. There exist other antialiasing methods (eg [EWA](http://graphics.cs.cmu.edu/projects/adpewa/index.html), stochastic sampling, mipmapping), but supersampling seemed the most convenient in our case, although it is slow. Any proper antialiasing method will requires the Jacobian. 

It is used in this repo when [applying a homographic (3x3 matrix) transform](https://github.com/NatronGitHub/openfx-supportext/blob/332f3caa9f5f6206ab39d202e56430633ee76eb6/ofxsTransform3x3Processor.h#L198) and in [other places](https://github.com/NatronGitHub/openfx-misc/search?q=ofxsFilterInterpolate2DSuper&unscoped_q=ofxsFilterInterpolate2DSuper).
