### ISSUE TITLE
Suggestion: Re-license to LGPL2

### ISSUE THREAD

**Issue by rodlie** [devernay/openfx-supportext#8]
I think it would benefit to re-license this project to LGPL2 (with a additional static exception, like FLTK) if possible, might help (attract more) plugin developers making (commercial) plugins for Natron. 

Just a suggestion.

**Comment by devernay** [comment]
Inria is the sole copyright owner on this repo, so only Inria can change the license

**Comment by rodlie** [comment]
Ok, was not sure.
