### ISSUE TITLE
Double denormalization of pixel during premult call

### ISSUE THREAD

**Issue by helospark** [devernay/openfx-supportext#9]
I'm trying to use Add effect from openfx-misc (in a custom host), however even adding a small value makes all colors entirely off (overflown).

I think this occurs in hosts where the max value is not 1.0 (aka. not kOfxBitDepthFloat), as far as I see the problem is the following:

[Add.cpp](https://github.com/NatronGitHub/openfx-misc/blob/master/Add/Add.cpp#L334) calls [ofxsPremultMaskMixPix](https://github.com/NatronGitHub/openfx-supportext/blob/e600cae7feb4c5becefcb2e25eea48eb9c991453/ofxsMaskMix.h#L492) with normalized floats, which calls these the functions:
 - [ofxsPremult](https://github.com/NatronGitHub/openfx-supportext/blob/e600cae7feb4c5becefcb2e25eea48eb9c991453/ofxsMaskMix.h#L306) that multiplies the normalized float with maxValue [0.0, 1.0] -> [0.0, maxValue]
 - [ofxsMaskMixPix](https://github.com/NatronGitHub/openfx-supportext/blob/e600cae7feb4c5becefcb2e25eea48eb9c991453/ofxsMaskMix.h#L427) which further calls [ofxsClampIfInt](https://github.com/NatronGitHub/openfx-supportext/blob/e600cae7feb4c5becefcb2e25eea48eb9c991453/ofxsMaskMix.h#L183) that also multiplies the already denormalized pixel value with maxValue [0.0, maxValue] -> [0.0, maxValue * maxValue].

To make these plugins work for all hosts one of the denormalization have to be removed. For example ofxsMaskMix.h:183
```
-    return (PIX)(ofxsClamp(v, min, max) * maxValue + 0.5);
+    return (PIX)(ofxsClamp(v, min, max) + 0.5);
```
this seems to fix many plugins, but I'm not sure if this causes any regression for the other plugins.

**Comment by devernay** [comment]
Thank you for testing the plugins on a non-float host, and for fixing bugs! Your feedback is very valuable.

**Comment by devernay** [comment]
https://github.com/helospark/tactview looks very interesting! You should advertise it on https://discuss.pixls.us/c/software/natron

**Comment by helospark** [comment]
Thanks for taking care of this so quickly.
I may use your tip one day :+1:
